# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Treat Me | Event Walls & Confectionery Company
description: > # this means to ignore newlines until "baseurl:"
  A family run events confectionary company based in Southampton. We provide event walls and confectionery for private parties and corporate events. We feel enhancing those special moments are important, for capturing a lifetime of memories. 
baseurl: "" # the subpath of your site, e.g. /blog
url:  # the base hostname & protocol for your site

# Markdown settings
markdown: kramdown

# Sass settings
sass:
  add_charset: true
  sass_dir: assets/sass
  style: :compressed

# Build settings
exclude:
  - package.json
  - README.md
  - CNAME

# Plugin settings
plugins:
  - jekyll-feed
  - jekyll-sitemap

incremental: true
